Bug 2047553 - Disable `-Wstringop-overread` if compiling with GCC  a=pascalc DONTBUILD
GCC considers the size of `constexpr mozilla::Span` to `0` and that
causes the following warning which is treated as error.
```
/usr/include/c++/10/bits/stl_algobase.h:105:32: error: 'int __builtin_memcmp_eq(const void*, const void*, long unsigned int)' specified bound 20 exceeds source size 0 [-Werror=stringop-overread]
  return __builtin_memcmp(__first1, __first2, sizeof(_Tp) * __num);
         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I don't know why this is caused by unifying
`TestFormattingAndStreaming.cpp` because it does not use `Span`.

Original Revision: https://phabricator.services.mozilla.com/D307209

Differential Revision: https://phabricator.services.mozilla.com/D307678